apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitlab-echo-template
spec:
  params:  # 定义参数，和 TriggerBinding 中的保持一致
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun  # 定义 TaskRun 模板
      metadata:
        generateName: gitlab-run-  # TaskRun 名称前缀
      spec:
        serviceAccountName: tekton-triggers-gitlab-sa
        taskRef:
          name: task1
        resources:
          inputs:
            - name: source  # 和 Task 中的资源名保持一直
              resourceSpec:  # 资源声明
                type: git
                params:
                  - name: revision
                    value: $(tt.params.gitrevision)  # 读取参数值
                  - name: url
                    value: $(tt.params.gitrepositoryurl)
          outputs:
            - name: builtImage
              resourceRef:
                name: registry-pipeline-resource
        workspaces:
          - name: cache
            persistentVolumeClaim:
              claimName: cache-pvc      
