apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: show
      image: ubuntu
      script: |
        #! /bin/bash
        ls -la $(inputs.resources.source.path)
      volumeMounts:
        - name: cache-pvc
          mountPath: /share
