apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-listener
spec:
  serviceAccountName: tekton-triggers-gitlab-sa
  triggers:
  - name: gitlab-push-events-trigger
    interceptors:
    - gitlab:
        secretRef:  # 引用 gitlab-secret 的 Secret 对象中的 secretToken 的值
          secretName: gitlab-secret 
          secretKey: secretToken
        eventTypes:
        - Push Hook  # 只接收 GitLab Push 事件
    bindings:
    - ref: gitlab-push-binding  # TriggerBinding 对象
    template:
      name: gitlab-echo-template  # TriggerTemplate 对象
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: el-gitlab-listener
spec:
  routes:
  - match: Host(`tekton-teigger.larryzeta.cc`)
    kind: Rule
    services:
    - name: el-gitlab-listener  # 关联 EventListener 服务
      port: 8080
