apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv1
  labels:
    app: vnc
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfsv1
  nfs:
    path: /nfs
    server: 68.168.140.36
