apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
  labels:
    app: vnc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
     app: vnc
  storageClassName: nfsv1
